spring.application.name=pro2kf2026
#server.port=8081

spring.datasource.url=jdbc:h2:~/pro2kf2026
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# --- MariaDB v Dockeru, aktualne nepouzita ---
#spring.datasource.url=jdbc:mariadb://localhost:3307/pro2kf2026?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=heslo123
#hibernate.dialect=org.hibernate.dialect.MariaDBDialect

